//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dola.Module.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://servis.turkiye.gov.tr/services/g2g/kdgm/test/uetdsesya")]
        public string dola_Module_tr_gov_turkiye_servis_UdhbUetdsEsyaWsService {
            get {
                return ((string)(this["dola_Module_tr_gov_turkiye_servis_UdhbUetdsEsyaWsService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://servis.turkiye.gov.tr/services/g2g/kdgm/test/uetdsesya")]
        public string KYS_Module_tr_gov_turkiye_servis_UdhbUetdsEsyaWsService {
            get {
                return ((string)(this["KYS_Module_tr_gov_turkiye_servis_UdhbUetdsEsyaWsService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://servis.turkiye.gov.tr/services/g2g/kdgm/uetdsesya")]
        public string dola_Module_tr_gov_turkiye_servisLive_UdhbUetdsEsyaWsService {
            get {
                return ((string)(this["dola_Module_tr_gov_turkiye_servisLive_UdhbUetdsEsyaWsService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://servis.turkiye.gov.tr/services/g2g/kdgm/uetdsesya")]
        public string gologdo_Module_tr_gov_turkiye_servisLive_UdhbUetdsEsyaWsService {
            get {
                return ((string)(this["gologdo_Module_tr_gov_turkiye_servisLive_UdhbUetdsEsyaWsService"]));
            }
        }
    }
}
